build: off

os: unstable

branches:
  only:
    - master

skip_tags: true

environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 8

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm
  - .\node_modules\.bin\npm install

test_script:
  - node --version
  - .\node_modules\.bin\npm --version
  - .\node_modules\.bin\npm test
